const Employee = [
	{
		username: 'john_doe',
		email: 'john.doe@example.com',
		password: '12345',
		tasks: [
			{
				taskTitle: 'Complete Onboarding',
				taskDesc: 'Finish the onboarding documents and submit them.',
				taskDate: '2024-10-22',
				category: 'HR',
				priority: 'High',
				active: true,
				newTask: false,
				completed: false,
				failed: false,
			},
			{
				taskTitle: 'Team Meeting',
				taskDesc: 'Attend the project kickoff meeting.',
				taskDate: '2024-10-23',
				category: 'Meetings',
				priority: 'Medium',
				active: true,
				newTask: true,
				completed: false,
				failed: false,
			},
			{
				taskTitle: 'Client Follow-Up',
				taskDesc: 'Send follow-up email to the client.',
				taskDate: '2024-10-24',
				category: 'Client Communication',
				priority: 'Low',
				active: false,
				newTask: false,
				completed: true,
				failed: false,
			},
		],
	},
	{
		username: 'jane_smith',
		email: 'jane.smith@example.com',
		password: '12345',
		tasks: [
			{
				taskTitle: 'Code Review',
				taskDesc: 'Review pull requests from team members.',
				taskDate: '2024-10-21',
				category: 'Development',
				priority: 'High',
				active: true,
				newTask: true,
				completed: false,
				failed: false,
			},
			{
				taskTitle: 'Documentation Update',
				taskDesc: 'Update project documentation.',
				taskDate: '2024-10-25',
				category: 'Documentation',
				priority: 'Medium',
				active: false,
				newTask: true,
				completed: false,
				failed: true,
			},
			{
				taskTitle: 'Bug Fixing',
				taskDesc: 'Fix reported bugs from testing.',
				taskDate: '2024-10-22',
				category: 'Development',
				priority: 'High',
				active: true,
				newTask: false,
				completed: true,
				failed: false,
			},
			{
				taskTitle: 'Team Training',
				taskDesc: 'Attend team training on new software tools.',
				taskDate: '2024-10-30',
				category: 'Training',
				priority: 'Low',
				active: true,
				newTask: true,
				completed: false,
				failed: false,
			},
		],
	},
	{
		username: 'michael_brown',
		email: 'michael.brown@example.com',
		password: '12345',
		tasks: [
			{
				taskTitle: 'System Testing',
				taskDesc: 'Perform end-to-end system testing for the new release.',
				taskDate: '2024-10-23',
				category: 'Testing',
				priority: 'High',
				active: true,
				newTask: false,
				completed: false,
				failed: false,
			},
			{
				taskTitle: 'Security Audit',
				taskDesc: 'Run a security audit on the system.',
				taskDate: '2024-10-26',
				category: 'Security',
				priority: 'Medium',
				active: false,
				newTask: false,
				completed: true,
				failed: false,
			},
			{
				taskTitle: 'Update Dependencies',
				taskDesc: 'Update outdated project dependencies.',
				taskDate: '2024-10-21',
				category: 'Development',
				priority: 'Low',
				active: true,
				newTask: false,
				completed: false,
				failed: false,
			},
		],
	},
	{
		username: 'emma_wilson',
		email: 'emma.wilson@example.com',
		password: '12345',
		tasks: [
			{
				taskTitle: 'Marketing Strategy',
				taskDesc: 'Create a marketing strategy for Q4.',
				taskDate: '2024-10-20',
				category: 'Marketing',
				priority: 'High',
				active: true,
				newTask: true,
				completed: false,
				failed: false,
			},
			{
				taskTitle: 'Social Media Plan',
				taskDesc: 'Draft social media content calendar.',
				taskDate: '2024-10-25',
				category: 'Marketing',
				priority: 'Medium',
				active: false,
				newTask: false,
				completed: true,
				failed: false,
			},
			{
				taskTitle: 'Client Pitch',
				taskDesc: 'Prepare the pitch for a potential client.',
				taskDate: '2024-10-22',
				category: 'Sales',
				priority: 'High',
				active: true,
				newTask: false,
				completed: false,
				failed: false,
			},
			{
				taskTitle: 'Budget Planning',
				taskDesc: "Plan budget for next quarter's marketing campaigns.",
				taskDate: '2024-10-28',
				category: 'Finance',
				priority: 'Low',
				active: true,
				newTask: true,
				completed: false,
				failed: false,
			},
			{
				taskTitle: 'Website Analytics',
				taskDesc: 'Analyze website traffic data and prepare report.',
				taskDate: '2024-10-30',
				category: 'Analytics',
				priority: 'Medium',
				active: true,
				newTask: true,
				completed: false,
				failed: false,
			},
		],
	},
];

const Admin = [
	{
		username: 'admin_user',
		email: 'admin@example.com',
		password: '12345',
	},
];
